openapi: 3.2.0
info:
  title: Ziina Health Check API
  version: 1.0.0
  description: Ziina payment platform REST API for the UAE.
  contact:
    name: Ziina Support
    email: support@ziina.com
    url: https://docs.ziina.com
servers:
- url: https://api-v2.ziina.com/api
  description: Ziina production API
security:
- bearer: []
tags:
- name: Health Check
  description: Service status.
paths:
  /status:
    get:
      operationId: HealthCheckController_getStatus
      parameters: []
      responses:
        '200':
          description: ''
      tags:
      - Health Check
      summary: Health check controller get status
      x-summary-source: derived
components:
  securitySchemes:
    bearer:
      scheme: bearer
      bearerFormat: JWT
      type: http
